export const initialCriativos = [
  {
    id: 'cria-1',
    nomeArquivo: 'CRIATIVO_01_DESTAQUE_CONVERSAO',
    status: 'Em Edição',
    editor: 'Ruan',
    gravacao: 'Estúdio / Tráfego',
    tag: 'Meta Ads',
    linkPastaBase: 'https://drive.google.com',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cria-2',
    nomeArquivo: 'CRIATIVO_02_UAI_VEICULOS_OFERTA',
    status: 'Aprovado',
    editor: 'Rafael',
    gravacao: 'Uai Veículos',
    tag: 'Google Ads',
    linkPastaBase: 'https://drive.google.com',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cria-3',
    nomeArquivo: 'CRIATIVO_03_DEPOIMENTO_ALUNOS',
    status: 'Fila',
    editor: 'Ruan',
    gravacao: 'Depoimentos',
    tag: 'Instagram',
    linkPastaBase: 'https://drive.google.com',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cria-4',
    nomeArquivo: 'CRIATIVO_04_ANALISE_DE_ANUNCIOS',
    status: 'Finalizado',
    editor: 'Rafael',
    gravacao: 'Tráfego Pago',
    tag: 'YouTube',
    linkPastaBase: 'https://drive.google.com',
    createdAt: new Date().toISOString(),
  },
]
